### ISSUE TITLE
NSM is waiting Init 0/2 then CrashLoopBackOff

### ISSUE THREAD

**Issue by meteccinar** [kubeslice/networkservicemesh#62]
Hi everyone, I'm install kubeslice with my config, I have 3 kind cluster (controller, worker1, worker2). When installing kubeslice components, nsm, spire server and agent are not up. As far as i understand spire server and agent don't up because of nsm. I check to logs for nsm pods but i didn't look any error or warning. But spire server has a error log. I shared the log below.

Spire Server Pod Log
48ec-9983-d51ee0ce348b service=entry.v1.Entry subsystem_name=api
time="2025-01-29T09:04:33Z" level=debug msg="Polling for bundle update" subsystem_name=bundle_client trust_domain=docker.nsm
time="2025-01-29T09:04:33Z" level=error msg="Error updating bundle" error="can't perform SPIFFE Authentication: local copy of bundle not found" subsystem_name=bundle_client trust_domain=docker.nsm
 
I consider this log's reason because of nsm is not up correctly. Also I shared my config below.

```
  configuration:
  cluster_configuration:
    kube_config_path: ./kubeconfig.yaml
    controller:
      name: kind-ctrl
      context_name: kind-ctrl
      kube_config_path: ./kubeconfig.yaml
    workers:
    - name: kind-w1
      context_name: kind-w1
    - name: kind-w2
      context_name: kind-w2
  kubeslice_configuration:
    project_name: x-central
  helm_chart_configuration:
    repo_alias: kubeslice
    repo_url: https://kubeslice.github.io/kubeslice/
    cert_manager_chart:
      chart_name: cert-manager
    controller_chart:
      chart_name: kubeslice-controller
    worker_chart:
      chart_name: kubeslice-worker

```

I didn't any solution.I'm waiting for your answer...
